### ISSUE TITLE
프로젝트 다운 부탁드립니다.

### ISSUE THREAD

**Issue by l10032503** [l10032503/Personal_Information#1]
현재 진행상황
Personal_information 메인클래스 start()메소드 구현
각 클래스(Contacts, ToDoList Appointments) 생성
다운받으신 후 각자 맡은 class에 작업하시면 됩니다.

**Comment by l10032503** [comment]
메인클래스 코드에 오류가 있어 수정했습니다.

**Comment by DyeonKim** [comment]
메인 클래스 print 문자열 내용만 깨지는 현상이 있었습니다. 혹시 한글로 작성하신 건지 궁금합니다.
그리고 수정해서 pull request 하긴 했으나 혹시 또 깨지지 않았나 확인 부탁드립니다 :)

**Comment by l10032503** [comment]
제 컴퓨터상에는 문제가 없는데 한글로 작성했던게 원인인 것 같네요ㅠ0ㅠ!! 오늘 오후에 확인 한 후 pull request 수락하겠습니다 감사합니다~!!
