### ISSUE TITLE
AppointmentLsit 클래스 작성 질문드립니다.

### ISSUE THREAD

**Issue by DyeonKim** [l10032503/Personal_Information#5]
Appointments 클래스 파일에 같이 작성하는 게 아니라 다른 클래스 파일을 작성하여 만들까 하는데 어떻게 생각하시나요?
클래스는 각자 파일마다 하나씩 생성하는 게 원칙이라고 들었는데 혹시나해서 질문드립니다 :)

**Comment by l10032503** [comment]
넵 저는 상관없습니다!!ㅎㅎ
