### ISSUE TITLE
메뉴 입력시 나오는 문장 수정

### ISSUE THREAD

**Issue by l10032503** [l10032503/Personal_Information#7]
메뉴를 입력할때 메뉴 번호를 입력하는 것인지 메뉴 이름을 입력하는 것인지 헷갈릴 수 있기 때문에 Choice=> 대신 Choice Number=>으로 바꾸는 것이 어떨까합니다!
@DyeonKim @JiwonCocoder

**Comment by DyeonKim** [comment]
확실히 헷갈릴 수 있겠네요. 수정에 찬성합니다!!
