### ISSUE TITLE
desgin specification과 system implementation이 차이날 때 주의사항

### ISSUE THREAD

**Issue by JiwonCocoder** [l10032503/Personal_Information#8]
교수님께 질문했던 것을 공유하려고 합니다.
design specification과 달라질 수는 있지만, 아예 갈아엎었다는 생각이 들 정도면 안된다고 하셨습니다.
그래서 class수만큼은 원래 design대로 유지해줘야 할 것 같습니다. 

+)저의 경우, ArrayList에 대한 getter&setter method를 ToDoList.java에 추가하였습니다. 
@DyeonKim 
@l10032503

**Comment by DyeonKim** [comment]
네 알겠습니다.
